# Generated by Django 4.2.17 on 2025-01-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_anime_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
