# Generated by Django 4.2.17 on 2025-01-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_animeentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeentry',
            name='anime_duration',
        ),
    ]
