# Generated by Django 4.2.17 on 2025-01-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_animeentry_anime_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField()),
                ('review_text', models.TextField()),
                ('recommendation', models.CharField(choices=[('recommends', 'Recommends'), ('mixed', 'Mixed Feelings'), ('not_recommended', 'Does Not Recommend')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.animeentry')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user_profile', 'anime_id')},
            },
        ),
    ]
